### ISSUE TITLE
Status $ref check

### ISSUE THREAD

**Issue by jasonh-n-austin** [jasonh-n-austin/swagger-api-checkstyle#3]
Validate that `schemaRef` in checkstyle matches value in `swagger.yaml`.
```
  status:
    200:
    default:
      schemaRef: "#/definitions/Error"
```
Swagger-parser will need to load without dereferencing in order to check `$ref` value.
