### ISSUE TITLE
Schema $ref check

### ISSUE THREAD

**Issue by jasonh-n-austin** [jasonh-n-austin/swagger-api-checkstyle#4]
Recurse all model fields, and see if name matches in checkstyle `schema/properties`. If so, ensure `format` and/or `schemaRef` match up to spec.

```
  schema:
    properties:
      - name: "^.*\\_?id"
        format: uuid
      - name: "image"
        format: uuid
      - name: "currency_code"
        format: currency
        schemaRef: "#/definitions/CurrencyCode"
      - name: "^.*\\_?uuid"
        format: uuid
      - name: "^.*\\_?email"
        format: email
```
